package:
  name: multinest
  version: "3.10"

source:
  git_url: https://github.com/JohannesBuchner/MultiNest.git 
  git_rev: f6c6df735dd78bae58e053522b04f26a21947591

requirements:
  build:
    - mkl
    - cmake
    - libgfortran


  run:
    - mkl
    - libgfortran


about:
  home: https://github.com/JohannesBuchner/MultiNest
  license: UNKNOWN
  summary: 'MultiNest is a Bayesian inference tool which calculates the evidence and explores the parameter space which may contain multiple posterior modes and pronounced (curving) degeneracies in moderately high dimensions.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
