package:
  name: cuba
  version: "4.2"

source:
  fn: Cuba-4.2.tar.gz
  url: http://www.feynarts.de/cuba/Cuba-4.2.tar.gz
  md5: a3eb0751d4872a3f86401694bc5bedae

requirements:
  build:
    - libgfortran
    - mkl

  run:
    - libgfortran
    - mkl

about:
  home: http://www.feynarts.de/cuba/
  license: GPLv3
  summary: 'The Cuba library offers a choice of four independent routines for multidimensional numerical integration: Vegas, Suave, Divonne, and Cuhre'
