FROM ubuntu:20.04 as pwa2000

SHELL ["/bin/bash", "-c"]

COPY ./install_pwa2000.sh ./
RUN ./install_pwa2000.sh

FROM pwa2000
ENV CUPY_VERSION=112

COPY ./install_python.sh ./
RUN ./install_python.sh

