package:
  name: pypwa
  version: "3.0.0"

source:
  git_rev: master
  git_url: https://github.com/JeffersonLab/PyPWA.git


requirements:
  build:
    - python>=3.6,<4
    - setuptools>=46
    - tqdm>=4.45,<5
    - iminuit>=1.3,<2
    - scipy>=1.4,<2
    - numpy>=1.18,<2
    - pyyaml>=5.3,<6
    - tabulate>=0.8,<1
    - appdirs>=1.4,<2
    - pytables>=3.6,<4
    - pandas>=1,<2
    - openpyxl>=3,<4
    - matplotlib>=3.1,<4
    - numexpr>=2.7,<3
  run:
    - python>=3.6,<4
    - setuptools>=46
    - tqdm>=4.45,<5
    - iminuit>=1.3,<2
    - scipy>=1.4,<2
    - numpy>=1.18,<2
    - pyyaml>=5.3,<6
    - tabulate>=0.8,<1
    - appdirs>=1.4,<2
    - pytables>=3.6,<4
    - pandas>=1,<2
    - openpyxl>=3,<4
    - matplotlib>=3.1,<4
    - numexpr>=2.7,<3


about:
  home: https://github.com/JeffersonLab/PyPWA
  license: GNU General Public License v3 (GPLv3)
  summary: "Pythonic Partial Wave Analysis Toolkit."
