package:
  name: pypwa
  version: "3.4.0"

source:
  git_rev: main
  git_url: https://github.com/JeffersonLab/PyPWA.git


requirements:
  build:
    - python>=3.6,<4
    - setuptools
  run:
    - python>=3.6,<4
    - tqdm
    - iminuit>=2
    - scipy
    - numpy
    - pyyaml
    - tabulate
    - appdirs
    - pytables
    - pandas
    - numexpr
    - cupy
    - emcee


about:
  home: https://github.com/JeffersonLab/PyPWA
  license: GNU General Public License v3 (GPLv3)
  summary: "Pythonic Partial Wave Analysis Toolkit."
