package:
  name: pytest-runner
  version: "1.0dev"

source:
  fn: pytest-runner-1.0dev.zip
  url: https://files.pythonhosted.org/packages/65/61/05c2ddff49beb3b25b6cc298b9f7bf20711409ed78996677902ad113d902/pytest-runner-1.0dev.zip
  md5: cec640e65a70b1b5b95c1c88fe3f1a5a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-runner = pytest-runner:main
    #
    # Would create an entry point called pytest-runner that calls pytest-runner.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - hgtools

  run:
    - python
    - setuptools

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/jaraco/pytest-runner
  license: UNKNOWN
  summary: 'UNKNOWN'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
